### ISSUE TITLE
`connectionString` prop is no longer available in 3.0

### ISSUE THREAD

**Issue by moltar** [ozum/pg-test-util#14]
Is there a reason why `connectionString` was dropped from the version 3?

See:

 - #6
 - https://github.com/ozum/pg-test-util/commit/50099a84284c3569a52e10625fae42e3038579f4

Thanks!

**Comment by ozum** [comment]
Hi @moltar.

Previous version;
* was executing queries using `knex.raw`, but the current version uses directly `pg` client.
* was creating a connection string manually. It adds complexity when I try to support every connection features of `node-postgres` client provided. The current version passes connection parameters from the user, directly `node-postgres` to support every connection feature.

As a result, we do not have a connection string at hand.

Regarding #6, you needed to get a `pg` client and I guess you are creating a new client using the connection string. I can expose the `pg` client if it is a must for your use case, but prefer to avoid it if not really required, because exposing non-must attributes, makes developing backward-compatible future versions harder as in the case of the connection string exposure.

Isn't it possible to create another `pg` client using the same details you provide to `pg-test-utils`?

**Comment by moltar** [comment]
Yeah, makes sense. Fair enough! :) I'll have to find a workaround. 

> Isn't it possible to create another pg client using the same details you provide to pg-test-utils?

Well, I _could_ mangle the URI string and replace the database name. Which is what I did in the past.

Also, I am not using a client, but using a Pool instead. So that's the main reason.

**Comment by moltar** [comment]
I'll close the issue, as it seems to be non-actionable at this point. But we can continue the conversation here, if necessary. Thanks for the explanation, btw.

**Comment by ozum** [comment]
I was using [pg-connection-string](https://www.npmjs.com/package/pg-connection-string). Maybe it could be useful for your use case.
