### ISSUE TITLE
Expose pg.Client

### ISSUE THREAD

**Issue by moltar** [ozum/pg-test-util#6]
Since this is a PostgreSQL-specific package, I think it would be useful to expose the native `pg` object.

It is currently possible to get it from `knex`, but it is untyped.

```ts
db.knex.client.pool
```

Where `client` is of type `any`.

**Comment by ozum** [comment]
I skimmed `knex` documentation, but could not see a public method which returns native `pg` client. Since I'm using `knex` to connect non-master databases, I don't have access to native `pg` client using public methods.

`db.knex.client.pool` is private. Is there a way to access `pg` client using public methods?

**Comment by moltar** [comment]
> Is there a way to access pg client using public methods?

Hm, yeah, I am not sure.

How about returning a connection string or a connection object suitable for Pg client?

**Comment by ozum** [comment]
That's possible. I added readonly `database.connectionString` attribute. It can be used to create a native connection. You can test it using latest version.

**Comment by moltar** [comment]
Thank you!
